#ifndef __MY_DEFINES__

#define __MY_DEFINES__

#define RETURN_SUCCESS 0
#define RETURN_WRONG_FORMAT 10
#define RETURN_EMPTY_FILE 20
#define RETURN_NO_FILE 30
#define RETURN_MEMORY_ERROR 40
#define RETURN_NOT_ENOUGH_ARGUMENTS 50
#define RETURN_EMPTY_FILE_AFTER 60
#define RETURN_WRONG_ARGUMENTS 70
#define RETURN_INPUT_ERROR 80

#define INPUT_BUFFER 50

#endif