#ifndef __MY_DEFINES__

#define __MY_DEFINES__

#define RETURN_SUCCESS 0
#define RETURN_WRONG_FORMAT 10
#define RETURN_EMPTY_FILE 20
#define RETURN_NO_FILE 30
#define RETURN_MEMORY_ERROR 40
#define RETURN_NOT_ENOUGH_ARGUMENTS 50
#define RETURN_EMPTY_FILE_AFTER 60
#define RETURN_WRONG_ARGUMENTS 70
#define RETURN_WRONG_HEADER 80
#define RETURN_HEADER_CALC 90
#define RETURN_WRONG_COORDS 100
#define RETURN_SAME_COORDS 110
#define RETURN_NO_ADDITION_SETUP 120
#define RETURN_NO_MULTIPLY_SETUP 130
#define RETURN_NO_DET_SETUP 140

#endif